package co.edu.uniquindio.pfinal.interfaz;

import co.edu.uniquindio.pfinal.extras.PanelFondo;
import co.edu.uniquindio.pfinal.extras.Excepcion;
import co.edu.uniquindio.pfinal.variables.Persona;
import co.edu.uniquindio.pfinal.variables.Empresa;
import java.awt.BorderLayout;
import javax.swing.table.DefaultTableModel;
import java.util.Iterator;
import javax.swing.JOptionPane;

public final class GuiAdmin extends javax.swing.JInternalFrame {

    private Empresa miEmpresa;
    private GuiProducto guiProducto;
    private Persona persona;
    private DefaultTableModel tabla;

    /**
     * Constructor
     *
     * @param e
     * @param p
     */
    public GuiAdmin(Empresa e, Persona p) {
        initComponents();
        miEmpresa = e;
        tabla = new DefaultTableModel();
        llenarTabla();
        mostrarDatos();
        this.persona = p;
        this.setVisible(true);
        jlImagen.setIcon(persona.getFoto()); //Cargar Imagen
        miEmpresa.calcularGanacias(persona); //ganancias

        PanelFondo F = new PanelFondo();
        this.add(F, BorderLayout.CENTER);
        this.pack();

        jID.setVisible(false);
        jTxtID.setVisible(false);
        jVincular.setVisible(false);
        jDesvincular.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jlImagen = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        JTpersonas = new javax.swing.JTable();
        jBtnCerrar = new javax.swing.JButton();
        jBtnModificar = new javax.swing.JButton();
        jToggleEstado = new javax.swing.JToggleButton();
        jID = new javax.swing.JLabel();
        jTxtID = new javax.swing.JTextField();
        jVincular = new javax.swing.JButton();
        jDesvincular = new javax.swing.JButton();
        jBtnAgregar = new javax.swing.JButton();
        jBtnArbol = new javax.swing.JButton();
        jBtnProductos = new javax.swing.JButton();
        jBtnComprar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setTitle("Administrador");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jlImagen.setText("                     Imagen");
        jlImagen.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        JTpersonas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(JTpersonas);

        jBtnCerrar.setText("Cerrar");
        jBtnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarActionPerformed(evt);
            }
        });

        jBtnModificar.setText("Modificar Datos");
        jBtnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnModificarActionPerformed(evt);
            }
        });

        jToggleEstado.setText("Estado");
        jToggleEstado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleEstadoActionPerformed(evt);
            }
        });

        jID.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jID.setForeground(new java.awt.Color(255, 255, 255));
        jID.setText("ID:");

        jTxtID.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtIDKeyTyped(evt);
            }
        });

        jVincular.setText("VINCULAR");
        jVincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jVincularActionPerformed(evt);
            }
        });

        jDesvincular.setText("DESVINCUALR");
        jDesvincular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jDesvincularActionPerformed(evt);
            }
        });

        jBtnAgregar.setText("Agregar Usuario");
        jBtnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAgregarActionPerformed(evt);
            }
        });

        jBtnArbol.setText("Arbol");
        jBtnArbol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnArbolActionPerformed(evt);
            }
        });

        jBtnProductos.setText("Productos");
        jBtnProductos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnProductosActionPerformed(evt);
            }
        });

        jBtnComprar.setText("Comprar");
        jBtnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnComprarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnCerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 444, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBtnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnArbol, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnComprar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jBtnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTxtID)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jVincular, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jToggleEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jDesvincular, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jBtnProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jDesvincular, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jID)
                                .addComponent(jTxtID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jVincular)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jToggleEstado)
                            .addComponent(jBtnAgregar)
                            .addComponent(jBtnProductos)))
                    .addComponent(jlImagen, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnCerrar)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnModificar)
                        .addComponent(jBtnArbol)
                        .addComponent(jBtnComprar)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarActionPerformed
        GUIPpal guiPpal = new GUIPpal();
        this.dispose();
    }//GEN-LAST:event_jBtnCerrarActionPerformed

    private void jBtnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnModificarActionPerformed
        GuiPersona guiPersona = new GuiPersona(miEmpresa, persona, 1, 0);
        this.dispose();
        GUIPpal.jEscritorio.add(guiPersona);
        guiPersona.toFront();
        guiPersona.setVisible(true);
    }//GEN-LAST:event_jBtnModificarActionPerformed

    private void jToggleEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleEstadoActionPerformed
        if (jToggleEstado.isSelected()) {
            jID.setVisible(true);
            jTxtID.setVisible(true);
            jVincular.setVisible(true);
            jDesvincular.setVisible(true);
        }
        if (!jToggleEstado.isSelected()) {
            jID.setVisible(false);
            jTxtID.setVisible(false);
            jVincular.setVisible(false);
            jDesvincular.setVisible(false);
        }

//        guiEstado = new GuiEstado(this, miEmpresa);
//        this.setVisible(false);
    }//GEN-LAST:event_jToggleEstadoActionPerformed

    private void jTxtIDKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtIDKeyTyped
        miEmpresa.espaciosVacios(evt, jTxtID);
        miEmpresa.noTeclearLetras(evt);
        miEmpresa.noteclearCaracteres(evt);
    }//GEN-LAST:event_jTxtIDKeyTyped

    private void jVincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jVincularActionPerformed
        try {
            String id = jTxtID.getText();
            if (id.equals(" ")) {
                throw new NullPointerException("LLENE EL CAMPO ID");
            }

            //capturamos el estado actual de la persona.
            boolean vinculo = miEmpresa.reactivarPersona(id);
            if (vinculo) {
                JOptionPane.showMessageDialog(null, "PERSONA REACTIVADA", "¡EXITO!", JOptionPane.INFORMATION_MESSAGE);
                llenarTabla();
                mostrarDatos();
                jTxtID.setText("");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "¡ERROR!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jVincularActionPerformed

    private void jDesvincularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jDesvincularActionPerformed
        try {
            String id = jTxtID.getText();
            if (id.equals(" ")) {
                throw new NullPointerException("LLENE EL CAMPO ID");
            }
            if (id.equalsIgnoreCase(miEmpresa.getArbol().getRaiz().getP().getCedula())) {
                throw new Excepcion("el administrador no se puede desvincular");
            }
            //capturamos el estado actual de la persona.
            boolean vinculo = miEmpresa.darDebaja(id);
            if (vinculo) {

                JOptionPane.showMessageDialog(null, "PERSONA DESACTIVADA", "¡EXITO!", JOptionPane.INFORMATION_MESSAGE);
                llenarTabla();
                mostrarDatos();
                jTxtID.setText("");
            }
        } catch (Excepcion mi) {
            miEmpresa.mostrarMensajeError(mi.getMessage());
        } catch (Exception e) {
            miEmpresa.mostrarMensajeError(e.getMessage());
        }
    }//GEN-LAST:event_jDesvincularActionPerformed

    private void jBtnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAgregarActionPerformed
        GuiPersona guiPersona = new GuiPersona(miEmpresa, persona, 0, 0);
        this.dispose();
        GUIPpal.jEscritorio.add(guiPersona);
        guiPersona.toFront();
        guiPersona.setVisible(true);
    }//GEN-LAST:event_jBtnAgregarActionPerformed

    private void jBtnProductosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnProductosActionPerformed
        guiProducto = new GuiProducto(this, miEmpresa, persona);
        this.dispose();
        GUIPpal.jEscritorio.add(guiProducto);
        guiProducto.toFront();
        guiProducto.setVisible(true);
    }//GEN-LAST:event_jBtnProductosActionPerformed

    private void jBtnArbolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnArbolActionPerformed
        GuiArbol guiArbol = new GuiArbol(miEmpresa, persona, persona);
        this.dispose();
        GUIPpal.jEscritorio.add(guiArbol);
        guiArbol.toFront();
        guiArbol.setVisible(true);
    }//GEN-LAST:event_jBtnArbolActionPerformed

    private void jBtnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnComprarActionPerformed
        GuiCompra guiCompra = new GuiCompra(miEmpresa, persona, 0);
        this.dispose();
        GUIPpal.jEscritorio.add(guiCompra);
        guiCompra.toFront();
        guiCompra.setVisible(true);
    }//GEN-LAST:event_jBtnComprarActionPerformed

    /**
     * Metodo que crea el diseño
     */
    public void llenarTabla() {

        String data[][] = {};
        String col[] = {"CEDULA", "CONTRASEÑA", "NOMBRE", "TELEFONO", "ESTADO"};
        tabla = new DefaultTableModel(data, col);
        JTpersonas.setModel(tabla);
    }

    /**
     * Metodo que llena y muestra los datos
     */
    public void mostrarDatos() {
        int con = 0;
        Iterator<Persona> persona = miEmpresa.getListaPersonas().iterator();
        while (persona.hasNext()) {
            Persona per = persona.next();
            if (per != null) {
                String cedula = per.getCedula();
                String contraseña = per.getContrasena();
                String nombre = per.getNombre() + " " + per.getApellido();
                String telefono = per.getTelefono();
                String esta2 = "";
                boolean estado = per.isIsActivo();
                if (estado) {
                    esta2 = "activo";
                } else {
                    esta2 = "inactivo";
                }
                tabla.insertRow(con, new Object[]{});
                tabla.setValueAt(cedula, con, 0);
                tabla.setValueAt(contraseña, con, 1);
                tabla.setValueAt(nombre, con, 2);
                tabla.setValueAt(telefono, con, 3);
                tabla.setValueAt(esta2, con, 4);
                con++;
            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable JTpersonas;
    private javax.swing.JButton jBtnAgregar;
    private javax.swing.JButton jBtnArbol;
    private javax.swing.JButton jBtnCerrar;
    private javax.swing.JButton jBtnComprar;
    private javax.swing.JButton jBtnModificar;
    private javax.swing.JButton jBtnProductos;
    private javax.swing.JButton jDesvincular;
    private javax.swing.JLabel jID;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JToggleButton jToggleEstado;
    private javax.swing.JTextField jTxtID;
    private javax.swing.JButton jVincular;
    private javax.swing.JLabel jlImagen;
    // End of variables declaration//GEN-END:variables
}
