package co.edu.uniquindio.pfinal.interfaz;

import co.edu.uniquindio.pfinal.extras.Constantes;
import co.edu.uniquindio.pfinal.variables.Persona;
import co.edu.uniquindio.pfinal.variables.Empresa;
import co.edu.uniquindio.pfinal.extras.Excepcion;
import co.edu.uniquindio.pfinal.extras.ImagenFondo;
import java.awt.Image;
import java.awt.Toolkit;

/**
 *
 * @author GALB007
 */
public class GUIPpal extends javax.swing.JFrame {

    private final Empresa miEmpresa;
    private Persona persona;
    private GuiAdmin guiAdmin;
    private GuiUsuario guiUsuario;
    private GuiPersona guiPersona;

    String usuario;
    String contrasena;

    public GUIPpal() {
        initComponents();
        //Fondo del escritorio (jEscritorio)
        jEscritorio.setBorder(new ImagenFondo());
        //extender el escritorio
//        this.setExtendedState(GUIPpal.MAXIMIZED_BOTH);

        jLayeredLogin.setVisible(false);
        jLayeredBonificacion.setVisible(false);

        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getResource(Constantes.DIRECTORIO_IMAGENES + Constantes.ICONOVENTANA));
        setIconImage(icon);

        miEmpresa = new Empresa();
        if (!miEmpresa.getArbol().isVacio()) {
            usuario = miEmpresa.getArbol().getRaiz().getP().getCedula();
            contrasena = miEmpresa.getArbol().getRaiz().getP().getContrasena();
            jBtnEntrar.setText("Ingresar");
            jTxtUsuario.setVisible(true);
            jTxtContraseña.setVisible(true);
            jLblCedula.setVisible(true);
            jLblContrasena.setVisible(true);
        } else {
            jBtnEntrar.setText("REGISTRARSE");
            jTxtUsuario.setVisible(false);
            jTxtContraseña.setVisible(false);
            jLblCedula.setVisible(false);
            jLblContrasena.setVisible(false);
        }
//        this.setVisible(true);
        System.out.println("DATOS ADMIN: " + "\nCedula: " + usuario + "\nContraseña: " + contrasena);

        JTxtNivel.setText("" + miEmpresa.getArbol().getNiveles());
        JTxtPorcentaje.setText("" + miEmpresa.getArbol().getPorcentaje());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jEscritorio = new javax.swing.JDesktopPane();
        jLayeredLogin = new javax.swing.JLayeredPane();
        jLblCedula = new javax.swing.JLabel();
        jTxtUsuario = new javax.swing.JTextField();
        jLblContrasena = new javax.swing.JLabel();
        jTxtContraseña = new javax.swing.JTextField();
        jBtnEntrar = new javax.swing.JButton();
        jBtnCerrarL = new javax.swing.JButton();
        jLayeredBonificacion = new javax.swing.JLayeredPane();
        jLblNivel = new javax.swing.JLabel();
        jLblPorcentaje = new javax.swing.JLabel();
        JTxtNivel = new javax.swing.JTextField();
        JTxtPorcentaje = new javax.swing.JTextField();
        jBtnCerrarB = new javax.swing.JButton();
        jBtnGuardar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuArchivo = new javax.swing.JMenu();
        jMenuLibro = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenuItem();
        jMenuVer = new javax.swing.JMenu();
        jMenuBonificacion = new javax.swing.JMenuItem();
        jMenuInfo = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Estructura Piramidal - UNIQUINDIO");
        setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        jEscritorio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jEscritorio.setMinimumSize(new java.awt.Dimension(600, 450));

        jLayeredLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white), "Login", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jLayeredLogin.setToolTipText("");
        jLayeredLogin.setName(""); // NOI18N

        jLblCedula.setForeground(new java.awt.Color(255, 255, 255));
        jLblCedula.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblCedula.setText("Cedula");

        jTxtUsuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtUsuarioKeyTyped(evt);
            }
        });

        jLblContrasena.setForeground(new java.awt.Color(255, 255, 255));
        jLblContrasena.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLblContrasena.setText("Contraseña");

        jTxtContraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTxtContraseñaKeyTyped(evt);
            }
        });

        jBtnEntrar.setText("Ingresar");
        jBtnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnEntrarActionPerformed(evt);
            }
        });

        jBtnCerrarL.setText("Cerrar");
        jBtnCerrarL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarLActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredLoginLayout = new javax.swing.GroupLayout(jLayeredLogin);
        jLayeredLogin.setLayout(jLayeredLoginLayout);
        jLayeredLoginLayout.setHorizontalGroup(
            jLayeredLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredLoginLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredLoginLayout.createSequentialGroup()
                        .addComponent(jBtnEntrar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jBtnCerrarL, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jLayeredLoginLayout.createSequentialGroup()
                        .addGroup(jLayeredLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblCedula, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLblContrasena))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jLayeredLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jLayeredLoginLayout.setVerticalGroup(
            jLayeredLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredLoginLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTxtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblCedula))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblContrasena)
                    .addComponent(jTxtContraseña, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCerrarL)
                    .addComponent(jBtnEntrar)))
        );
        jLayeredLogin.setLayer(jLblCedula, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredLogin.setLayer(jTxtUsuario, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredLogin.setLayer(jLblContrasena, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredLogin.setLayer(jTxtContraseña, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredLogin.setLayer(jBtnEntrar, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredLogin.setLayer(jBtnCerrarL, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jLayeredBonificacion.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.LOWERED, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white, java.awt.Color.white), "Bonificación", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14), new java.awt.Color(255, 255, 255))); // NOI18N
        jLayeredBonificacion.setToolTipText("");
        jLayeredBonificacion.setName(""); // NOI18N

        jLblNivel.setForeground(new java.awt.Color(255, 255, 255));
        jLblNivel.setText("Niveles:");

        jLblPorcentaje.setForeground(new java.awt.Color(255, 255, 255));
        jLblPorcentaje.setText("Porcentaje:");

        JTxtNivel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtNivelKeyTyped(evt);
            }
        });

        JTxtPorcentaje.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                JTxtPorcentajeKeyTyped(evt);
            }
        });

        jBtnCerrarB.setText("Cerrar");
        jBtnCerrarB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCerrarBActionPerformed(evt);
            }
        });

        jBtnGuardar.setText("Aceptar");
        jBtnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jLayeredBonificacionLayout = new javax.swing.GroupLayout(jLayeredBonificacion);
        jLayeredBonificacion.setLayout(jLayeredBonificacionLayout);
        jLayeredBonificacionLayout.setHorizontalGroup(
            jLayeredBonificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredBonificacionLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jLayeredBonificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jLayeredBonificacionLayout.createSequentialGroup()
                        .addGroup(jLayeredBonificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblNivel)
                            .addComponent(jLblPorcentaje))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jLayeredBonificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(JTxtPorcentaje, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                            .addComponent(JTxtNivel)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jLayeredBonificacionLayout.createSequentialGroup()
                        .addComponent(jBtnGuardar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                        .addComponent(jBtnCerrarB)))
                .addContainerGap())
        );
        jLayeredBonificacionLayout.setVerticalGroup(
            jLayeredBonificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jLayeredBonificacionLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jLayeredBonificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNivel, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(JTxtNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredBonificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JTxtPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLblPorcentaje, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jLayeredBonificacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCerrarB)
                    .addComponent(jBtnGuardar)))
        );
        jLayeredBonificacion.setLayer(jLblNivel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredBonificacion.setLayer(jLblPorcentaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredBonificacion.setLayer(JTxtNivel, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredBonificacion.setLayer(JTxtPorcentaje, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredBonificacion.setLayer(jBtnCerrarB, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jLayeredBonificacion.setLayer(jBtnGuardar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jEscritorioLayout = new javax.swing.GroupLayout(jEscritorio);
        jEscritorio.setLayout(jEscritorioLayout);
        jEscritorioLayout.setHorizontalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLayeredLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLayeredBonificacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(308, Short.MAX_VALUE))
        );
        jEscritorioLayout.setVerticalGroup(
            jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEscritorioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLayeredLogin)
                    .addComponent(jLayeredBonificacion))
                .addContainerGap(356, Short.MAX_VALUE))
        );
        jEscritorio.setLayer(jLayeredLogin, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jEscritorio.setLayer(jLayeredBonificacion, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jMenuBar1.setToolTipText("");
        jMenuBar1.setName(""); // NOI18N

        jMenuArchivo.setText("Archivo");

        jMenuLibro.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        jMenuLibro.setText("Login");
        jMenuLibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuLibroActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuLibro);

        jMenuSalir.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0));
        jMenuSalir.setText("Salir");
        jMenuSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuSalirActionPerformed(evt);
            }
        });
        jMenuArchivo.add(jMenuSalir);

        jMenuBar1.add(jMenuArchivo);

        jMenuVer.setText("Ver");

        jMenuBonificacion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_B, java.awt.event.InputEvent.CTRL_MASK));
        jMenuBonificacion.setText("Bonificación");
        jMenuBonificacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuBonificacionActionPerformed(evt);
            }
        });
        jMenuVer.add(jMenuBonificacion);

        jMenuBar1.add(jMenuVer);

        jMenuInfo.setText("Info");
        jMenuBar1.add(jMenuInfo);

        setJMenuBar(jMenuBar1);
        jMenuBar1.getAccessibleContext().setAccessibleName("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jEscritorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        //jLayeredLogin.setVisible(false);
        //jLayeredBonificacion.setVisible(false);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuLibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuLibroActionPerformed
        jLayeredLogin.setVisible(true);
    }//GEN-LAST:event_jMenuLibroActionPerformed

    private void jMenuSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jMenuSalirActionPerformed

    private void jBtnCerrarLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarLActionPerformed
        jLayeredLogin.setVisible(false);
    }//GEN-LAST:event_jBtnCerrarLActionPerformed

    private void jTxtUsuarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUsuarioKeyTyped
        miEmpresa.espaciosVacios(evt, jTxtContraseña);
    }//GEN-LAST:event_jTxtUsuarioKeyTyped

    private void jTxtContraseñaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtContraseñaKeyTyped
        miEmpresa.espaciosVacios(evt, jTxtContraseña);
    }//GEN-LAST:event_jTxtContraseñaKeyTyped

    private void jBtnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnEntrarActionPerformed
        if (!miEmpresa.getArbol().isVacio()) {
            try {
                String Cedula = jTxtUsuario.getText();
                Persona per = miEmpresa.getArbol().buscarPersona(Cedula, miEmpresa.getArbol().getRaiz()).getP();
                if (Cedula.equals("")) {
                    throw new NullPointerException("Ingrese su Cedula");
                }
                String Contraseña = jTxtContraseña.getText();
                if (Contraseña.equals("")) {
                    throw new NullPointerException("Ingrese la contraseña");
                }
                if (Cedula.equalsIgnoreCase(usuario) && Contraseña.equalsIgnoreCase(contrasena)) {
                    miEmpresa.mostrarMensaje("BIENVENIDO " + per.getNombre() + " " + per.getApellido());
                    guiAdmin = new GuiAdmin(this.miEmpresa, per);
                    GUIPpal.jEscritorio.add(guiAdmin);
                    guiAdmin.toFront();
                    guiAdmin.setVisible(true);

                } else if (per.getCedula().equalsIgnoreCase(Cedula) && per.getContrasena().equalsIgnoreCase(Contraseña)) {
                    guiUsuario = new GuiUsuario(miEmpresa, per);
                    GUIPpal.jEscritorio.add(guiUsuario);
                    guiUsuario.toFront();
                    guiUsuario.setVisible(true);
                } else {
                    throw new Excepcion("Instenlo de nuevo");
                }
            } catch (Excepcion | NullPointerException n) {
                if (n.getMessage() != null) {
                    miEmpresa.mostrarMensajeError(n.getMessage());
                } else {
                    miEmpresa.mostrarMensajeError("Datos incorrectos");
                }
            } catch (Exception e) {
                miEmpresa.mostrarMensajeError(e.getMessage());
            }
        } else {
            jLayeredLogin.setVisible(false);
            jBtnEntrar.setText("Ingresar");
            jTxtUsuario.setVisible(true);
            jTxtContraseña.setVisible(true);
            jLblCedula.setVisible(true);
            jLblContrasena.setVisible(true);
            miEmpresa.mostrarMensaje("Es la primer persona en el arbol");
            guiPersona = new GuiPersona(miEmpresa, null, 0, 0);
            GUIPpal.jEscritorio.add(guiPersona);
            guiPersona.setVisible(true);

        }
    }//GEN-LAST:event_jBtnEntrarActionPerformed

    private void jBtnCerrarBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCerrarBActionPerformed
        jLayeredBonificacion.setVisible(false);
    }//GEN-LAST:event_jBtnCerrarBActionPerformed

    private void JTxtPorcentajeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtPorcentajeKeyTyped
        miEmpresa.noTeclearLetras(evt);
        miEmpresa.espaciosVacios(evt, JTxtPorcentaje);
        miEmpresa.noteclearCaracteres(evt);
    }//GEN-LAST:event_JTxtPorcentajeKeyTyped

    private void JTxtNivelKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_JTxtNivelKeyTyped
        miEmpresa.noTeclearLetras(evt);
        miEmpresa.espaciosVacios(evt, JTxtPorcentaje);
        miEmpresa.noteclearCaracteres(evt);
    }//GEN-LAST:event_JTxtNivelKeyTyped

    private void jBtnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnGuardarActionPerformed
        String nivel = JTxtNivel.getText();
        int lvl = Integer.parseInt(nivel);
        String por = JTxtPorcentaje.getText();
        double p = Double.parseDouble(por);
        miEmpresa.getArbol().setNiveles((lvl));
        miEmpresa.getArbol().setPorcentaje(p);
        miEmpresa.mostrarMensaje("configuración actualizada");
        miEmpresa.borrarFichero(miEmpresa.getArchivoArbol());
        miEmpresa.serializarArbol(miEmpresa.getArchivoArbol(), miEmpresa.getArbol());
    }//GEN-LAST:event_jBtnGuardarActionPerformed

    private void jMenuBonificacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuBonificacionActionPerformed
        jLayeredBonificacion.setVisible(true);
    }//GEN-LAST:event_jMenuBonificacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metal".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUIPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUIPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUIPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUIPpal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new GUIPpal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField JTxtNivel;
    private javax.swing.JTextField JTxtPorcentaje;
    private javax.swing.JButton jBtnCerrarB;
    private javax.swing.JButton jBtnCerrarL;
    private javax.swing.JButton jBtnEntrar;
    private javax.swing.JButton jBtnGuardar;
    public static javax.swing.JDesktopPane jEscritorio;
    private javax.swing.JLayeredPane jLayeredBonificacion;
    private javax.swing.JLayeredPane jLayeredLogin;
    private javax.swing.JLabel jLblCedula;
    private javax.swing.JLabel jLblContrasena;
    private javax.swing.JLabel jLblNivel;
    private javax.swing.JLabel jLblPorcentaje;
    private javax.swing.JMenu jMenuArchivo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuBonificacion;
    private javax.swing.JMenu jMenuInfo;
    private javax.swing.JMenuItem jMenuLibro;
    private javax.swing.JMenuItem jMenuSalir;
    private javax.swing.JMenu jMenuVer;
    private javax.swing.JTextField jTxtContraseña;
    private javax.swing.JTextField jTxtUsuario;
    // End of variables declaration//GEN-END:variables
}
